### ISSUE TITLE
[bug | 0.5.0] Quarry upgrades getting deleted

### ISSUE THREAD

**Issue by Link250** [TED-inc/FabricQuarry#26] opened 2021-10-30 17:28 UTC
**Description**
When breaking the Quarry, any Quarry Upgrades like Silk Touch or Fortune get destroyed while other Upgrades like Overclocker or Transformer get dropped. (Might be related but hasn't been tested) After a Server restart these Upgrades were also missing from the quarry and it's progress was reset, causing it to start mining through it's own tubes again, destroying the previously placed tubes in the process.

**To Reproduce**
Simply place any Quarry Upgrades into their special slots and break the Quarry with a suitable pickaxe.

**Expected behavior**
The Quarry Upgrades should be dropped as Items just like the other Upgrades or blocks inside the Quarry get dropped when breaking it.

**Mods versions:**
 - quarry-reborn-1.17-0.5.0
 - TechReborn-5.0.9-beta+build.131
 - fabric-api-0.41.0+1.17

**Comment by TED-inc** [comment] 2021-10-31 07:01
Thx for detailed report, I will look on it.

**Comment by TED-inc** [comment] 2021-10-31 07:05
Could u write more detailed about 

> After a Server restart these Upgrades were also missing from the quarry and it's progress was reset, causing it to start mining through it's own tubes again, destroying the previously placed tubes in the process.

I can't reproduce it

**Comment by TED-inc** [comment] 2021-10-31 10:55
Main issue fixed in 0.5.1

**Comment by Link250** [comment] 2021-10-31 17:26
Thank you very much for the fix !

About the other Issue:
I just set up a completely fresh 1.17.1 Server with Fabric 0.11.7 and only these mods:
- fabric-api-0.41.0+1.17
- quarry-reborn-1.17-0.5.1
- RebornCore-5.0.9-beta+build.131
- TechReborn-5.0.9-beta+build.131

I filled up a Quarry with a Silk Touch Upgrade, Overclocker Upgrade, Stone as Filler Blocks, Tubes and powered it with an Ultimate Solar Panel ![2021-10-31_18 14 42](https://user-images.githubusercontent.com/4541950/139594904-4a6d5339-2d8a-4d44-b32f-a3f1be51db5f.png)
Then i stopped the Server with the "stop" command and after starting it back up again the Quarry was missing all the items.

**Comment by TED-inc** [comment] 2021-10-31 21:34
Could you test it with some other blocks from tech reborn? Like matter fabricator, or compressor. Are they have similar issues?

**Comment by TED-inc** [comment] 2021-11-01 07:52
Maybe your world just don't save? U can check it, by adding items in your inventory, save world, then put them in quarry and stop server. If after restart your items will be in your inventory - this just mean that world wasn't saved

**Comment by Link250** [comment] 2021-11-01 12:37
Other tech reborn blocks seem to be fine (Tested Matter Fabricator, Compressor and Electric Furnace) and my inventory and other blocks in the world get saved too, only the Quarry is affected. Also i noticed some warnings in the server log that might be relevant and help finding the cause (https://pastebin.com/Wk5fEPEx), especially lines 59 and 83.

**Comment by TED-inc** [comment] 2021-11-01 15:29
I think problem is in line 83

**Comment by TED-inc** [comment] 2021-11-01 15:37
Could you try previous version of quarry mod (fe 0.4.4). Is it have similar issue?

**Comment by Link250** [comment] 2021-11-02 17:07
Tried using 0.4.4 and it had the same problem (https://pastebin.com/iUMMbwhs) i also made sure to create a new world and such to test it with in case the old one still had any issues.

**Comment by itsdinkd** [comment] 2021-11-04 02:41
Items are getting deleted when server restarts or you leave your world.

**Comment by TED-inc** [comment] 2021-11-05 06:25
@red2blue U can reproduce it in single player? Do you have a steps to reproduce?

**Comment by TED-inc** [comment] 2021-11-05 11:39
I finally found solution, so it fixed in 0.5.2 🎉. Please, check it

**Comment by Link250** [comment] 2021-11-07 03:34
That seems to have fixed the issue for me, thank you very much !

**Closed as completed** 2021-11-07 06:08 UTC
Labels: bug
